blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/gowdhamp/scaffoldr/discussions
    about: Please ask and answer questions here
  - name: Documentation
    url: https://github.com/gowdhamp/scaffoldr/wiki
    about: Check the wiki for guides and documentation